results_dir:
  # /scratch/siebrenf/lore3
  /bank/experiments/2025-03-lore
www_dir:
  # /vol/mbdata/siebrenf/lore
  /mnt/cn/vol/mbdata/siebrenf/lore
samples:
  - segmented

genome_fasta:
  # /scratch/siebrenf/lore/GRCh38/GRCh38.fa
  /bank/genomes/GRCh38/GRCh38.fa
gene_annotation_gtf:
  # /scratch/siebrenf/lore/GRCh38/GRCh38.annotation.gtf
  /bank/genomes/GRCh38/GRCh38.annotation.gtf
solote_genome: "hg38"
mitochondria: "chrM"

adapters:
  # Sequencing adapters.
  #   Docs: https://skera.how/adapters
  https://downloads.pacbcloud.com/public/dataset/Kinnex-single-cell-RNA/REF-MAS_adapters/MAS-Seq_Adapter_v1/mas16_primers.fasta

primers:
  # Sequencing primers.
  #  Docs: https://isoseq.how/umi/cli-workflow.html#step-2---primer-removal
  https://downloads.pacbcloud.com/public/dataset/Kinnex-single-cell-RNA/REF-10x_primers/10x_5kit_primers.fasta

barcodes:
  # Cell/molecular barcodes.
  #  Docs: https://isoseq.how/umi/cli-workflow.html#step-5---cell-barcode-correction-and-real-cell-identification
  # https://downloads.pacbcloud.com/public/dataset/Kinnex-single-cell-RNA/REF-10x_barcodes/3M-5pgex-jan-2023.REVCOMP.txt.gz
  https://downloads.pacbcloud.com/public/dataset/Kinnex-single-cell-RNA/REF-10x_barcodes/3M-3pgex-may-2023.REVCOMP.txt.gz

lima: "--isoseq --peek-guess"
# Barcoding design.
#  Specifies which bases to use as cell/molecular barcodes.
#  Docs:
#    - https://isoseq.how/umi/umi-barcode-design.html
#    - https://isoseq.how/umi/cli-workflow.html#step-3---tag
#    - https://kb.10xgenomics.com/hc/en-us/articles/360001493051-What-is-a-template-switch-oligo-TSO
isoseq_tag: "--design 16B-10U-13X-T"
isoseq_refine: ""  # --require-polya
isoseq_bcstats: "--molecular"
isoseq_bcstats_percentiles: 95
pigeon_classify: ""

# Optional outputs
bigwigs: True
qc_report: True  # recommended
