name: lore
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python
  - conda-forge::mamba
  - bioconda::snakemake
  - conda-forge::conda-ecosystem-user-package-isolation=1.0

  # dev
  - conda-forge::black
  - conda-forge::isort
  - bioconda::snakefmt
