from snakemake.io import expand

include: "configuration.smk"
include: "download.smk"
include: "0_skera.smk"
include: "1_lima.smk"
include: "2_isoseq.smk"


rule all:
    input:
        [f'{config["dedup_dir"]}/{sample}.bam' for sample in config["samples"]]
