custom_data:  # https://docs.seqera.io/multiqc/custom_content#section-configuration
  general_stats:
    plot_type: "generalstats"
  skera:
    id: "skera"
    section_name: "Skera"
    description: "TODO: Skera description"
    plot_type: "table"  # generalstats | table | bargraph | linegraph | boxplot | scatter | heatmap | violin
  lima:
    section_name: "Lima"
    description: "TODO: Lima description"
  isoseq:
    section_name: "Iso-seq"
    description: "TODO: Iso-seq description"
    plot_type: "table"

sp:
  general_stats:
    fn: "*general_stats*.txt"
  skera:
    fn: "multiqc_skera_summary.txt"
  lima:
    fn: "multiqc_lima.tsv"
  isoseq:
    fn: "multiqc_isoseq.tsv"

table_columns_visible:
  general_stats:
    m_hifi_reads: True
    m_s_reads: True
    avg_len_s_reads: False
    pct_full_array: False
    avg_array_size: False
  skera:
    m_hifi_reads: True
    m_s_reads: True
    avg_len_s_reads: True
    pct_full_array: True
    avg_array_size: True
