# module_order:
#   - reads_per_step
#   - skera
#   - lima
#   - isoseq_correct
#   - samtools
#   - isoseq_collapse

report_section_order:
  reads_per_step:
    order: 1000
  skera:
    order: 999
  lima:
    order: 998
  isoseq_correct:
    order: 997
  knee_plots:
    order: 997
  samtools:
    order: 996
  isoseq_collapse:
    order: 995

custom_data:  # https://docs.seqera.io/multiqc/custom_content#section-configuration
  reads_per_step:
    id: "reads_per_step"
    section_name: "Reads per processing step"
    description: "The number of reads found after each processing step. 
    1: Circular consensus sequencing (HiFi) reads. 
    2: Segmented reads. 
    3: Primed reads.
    5: Non-Chimeric reads. 
    6: PolyA-tailed reads. 
    7: Barcoded reads.
    8: Final reads."
    plot_type: "linegraph"  # generalstats | table | bargraph | linegraph | boxplot | scatter | heatmap | violin
    pconfig:
      logswitch: True
      logswitch_active: True
      logswitch_label: "Log10"
      ylab: "number of reads"
      xlab: "processing step"
      categories: True
  skera:
    id: "skera"
    section_name: "Skera"
    description: "Deconcatenates Kinnex HiFi reads to produce S-reads that represent the original cDNA molecules."
    plot_type: "table"
  lima:
    id: "lima"
    section_name: "Lima"
    description: "Removes and spurious false positives."
    plot_type: "table"
  isoseq_correct_stats:
    parent_id: "isoseq_correct"
    parent_name: "Iso-seq correct"
    parent_description: "Identifies cell barcode errors and corrects them. Additionally, Iso-seq correct estimates which reads are likely to originate from real cells vs ambrient RNA."
    id: "isoseq_correct_stats"
    section_name: "Stats"
    plot_type: "table"
  isoseq_correct_barcodes:
    id: "isoseq_correct_barcodes"
    parent_id: "isoseq_correct"
    section_name: "Barcode corrections"
    plot_type: "bargraph"
    description: "The number of barcodes with corrected barcode mismatches."
  isoseq_bcstats:
    id: "isoseq_bcstats"
    parent_id: "isoseq_correct"
    section_name: "Barcode stats"
    plot_type: "table"
  knee_plots:
    id: "knee_plots"
    parent_id: "isoseq_correct"
    section_name: "Knee plots"
    description: "The pink line shows the real cells labeled. See [here](https://isoseq.how/umi/cell-calling.html#cell-calling-documentation)."
  isoseq_collapse:
    id: "isoseq_collapse"
    section_name: "Iso-seq collapse"
    plot_type: "table"
    description: "Collapses redundant transcripts into unique isoforms based on exonic structures."

sp:
  reads_per_step:
    fn: "reads_per_step.tsv"
  skera:
    fn: "skera.tsv"
  lima:
    fn: "lima.tsv"
  isoseq_correct_stats:
    fn: "isoseq_correct.tsv"
  isoseq_correct_barcodes:
    fn: "isoseq_correct_barcodes.tsv"
  isoseq_bcstats:
    fn: "isoseq_bcstats.tsv"
  knee_plots:
    fn: "*.knee_mqc.png"
  isoseq_collapse:
    fn: "isoseq_collapse.tsv"
ignore_images: false

table_columns_visible:
  "Samtools: stats":
    error_rate: True
    non-primary_alignments: False
    reads_mapped: False
    reads_mapped_percent: True
    reads_properly_paired_percent: False
    reads_MQ0_percent: True
    raw_total_sequences: True
    insert_size_average: False

samtools_coverage:
  # tips: https://docs.seqera.io/multiqc/modules/samtools#coverage
  # show_excluded_debug_logs: True
  exclude_contigs:
    - "*_alt"
    - "*_decoy"
    - "*_random"
    - "chrUn*"
    - "HLA*"
    - "chrM"
    - "chrEBV"

extra_fn_clean_exts:
  - type: "truncate"
    pattern: ".coverage.tsv"
    module: samtools
